spring:
  application:
    name: billing-service
  datasource:
    url: ${DB_URL:${DATABASE_URL:jdbc:postgresql://${DB_HOST:${POSTGRES_HOST:localhost}}:${DB_PORT:${POSTGRES_PORT:5433}}/${DB_NAME:${POSTGRES_DB:billing_service}}}}
    username: ${DB_USERNAME:${DATABASE_USERNAME:${DB_USER:${POSTGRES_USER:postgres}}}}
    password: ${DB_PASSWORD:${DATABASE_PASSWORD:${POSTGRES_PASSWORD:postgres}}}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DB_SCHEMA:public}
  flyway:
    enabled: true
    schemas: ${DB_SCHEMA:public}
    default-schema: ${DB_SCHEMA:public}
    create-schemas: true

server:
  error:
    include-message: always

logging:
  level:
    com.doistech.billingservice: INFO
    org.flywaydb: INFO

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /swagger-ui.html

app:
  security:
    api-key-header: X-API-Key
    api-key: ${INTERNAL_API_KEY}

mercado-pago:
  base-url: ${MERCADO_PAGO_BASE_URL:https://api.mercadopago.com}
  access-token: ${MERCADO_PAGO_ACCESS_TOKEN:APP_USR-2169667340333844-070914-b0d074191686a4c213d60cd5048b727d-3313854838}
  public-key: ${MERCADO_PAGO_PUBLIC_KEY:APP_USR-dd97f0c7-e6be-4a5d-9ba6-ae726620b0f6}
  webhook-secret: ${MERCADO_PAGO_WEBHOOK_SECRET:43bbfd800b697bfb3ae9742f999906656bd1eda75a9be9c3b5f94c283798aeaa}
  notification-url: ${APP_BASE_URL:http://localhost:8080}/api/webhooks/mercado-pago
